export const quizQuestions = [
  {
    id: 1,
    technology: "html",
    level: "Beginner",
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Text Machine Language",
      "Hyperlinks Text Mark Language",
      "Home Tool Markup Language",
    ],
    correctAnswer: "Hyper Text Markup Language",
  },
  {
    id: 2,
    technology: "html",
    level: "Intermediate",
    question: "Which HTML tag is used to embed a video?",
    options: ["<media>", "<movie>", "<video>", "<embed>"],
    correctAnswer: "<video>",
  },
  {
    id: 3,
    technology: "html",
    level: "Pro",
    question: "Which attribute improves accessibility for images?",
    options: ["title", "src", "alt", "href"],
    correctAnswer: "alt",
  },
  // HTML - Beginner
  {
    id: 19,
    technology: "html",
    level: "Beginner",
    question: "Which tag is used for the largest heading?",
    options: ["<h6>", "<head>", "<h1>", "<heading>"],
    correctAnswer: "<h1>",
  },
  {
    id: 20,
    technology: "html",
    level: "Beginner",
    question: "What is the correct HTML tag for inserting a line break?",
    options: ["<break>", "<lb>", "<br>", "<newline>"],
    correctAnswer: "<br>",
  },
  {
    id: 21,
    technology: "html",
    level: "Beginner",
    question: "Which HTML element defines the title of a document?",
    options: ["<meta>", "<title>", "<head>", "<body>"],
    correctAnswer: "<title>",
  },
  {
    id: 22,
    technology: "html",
    level: "Beginner",
    question: "Which attribute is used to provide an advisory text for an element or its contents?",
    options: ["data", "info", "title", "alt"],
    correctAnswer: "title",
  },
  {
    id: 23,
    technology: "html",
    level: "Beginner",
    question: "Which HTML tag is used to define an unordered list?",
    options: ["<ol>", "<li>", "<dl>", "<ul>"],
    correctAnswer: "<ul>",
  },
  {
    id: 24,
    technology: "html",
    level: "Beginner",
    question: "What is the purpose of the <a> tag?",
    options: ["To add an image", "To create a paragraph", "To create a hyperlink", "To define a division"],
    correctAnswer: "To create a hyperlink",
  },
  {
    id: 25,
    technology: "html",
    level: "Beginner",
    question: "Which HTML element is used to specify a footer for a document or section?",
    options: ["<bottom>", "<footer>", "<end>", "<section>"],
    correctAnswer: "<footer>",
  },
  {
    id: 26,
    technology: "html",
    level: "Beginner",
    question: "Which tag is used to make text bold?",
    options: ["<i>", "<bold>", "<strong>", "<p>"],
    correctAnswer: "<strong>",
  },
  {
    id: 27,
    technology: "html",
    level: "Beginner",
    question: "Which HTML element is used for short quotations?",
    options: ["<blockquote>", "<q>", "<quote>", "<cite>"],
    correctAnswer: "<q>",
  },
  {
    id: 28,
    technology: "html",
    level: "Beginner",
    question: "What is the correct HTML for adding a background color?",
    options: ["<body bg='yellow'>", "<background>yellow</background>", "<body style='background-color:yellow;'>", "<body color='yellow'>"],
    correctAnswer: "<body style='background-color:yellow;'>",
  },
  // HTML - Intermediate
  {
    id: 29,
    technology: "html",
    level: "Intermediate",
    question: "Which HTML5 element is used to draw graphics on the fly?",
    options: ["<svg>", "<canvas>", "<draw>", "<graphic>"],
    correctAnswer: "<canvas>",
  },
  {
    id: 30,
    technology: "html",
    level: "Intermediate",
    question: "What is the purpose of the <meta> tag with charset attribute?",
    options: ["To define keywords", "To declare document encoding", "To set viewport", "To refresh the page"],
    correctAnswer: "To declare document encoding",
  },
  {
    id: 31,
    technology: "html",
    level: "Intermediate",
    question: "Which input type is used for email addresses?",
    options: ["text", "mail", "email", "url"],
    correctAnswer: "email",
  },
  {
    id: 32,
    technology: "html",
    level: "Intermediate",
    question: "What does the HTML <aside> element represent?",
    options: ["A section of navigation links", "Content separate from the main content", "A sidebar with related information", "A footer for the document"],
    correctAnswer: "Content separate from the main content",
  },
  {
    id: 33,
    technology: "html",
    level: "Intermediate",
    question: "Which HTML element is used to define important text?",
    options: ["<i>", "<b>", "<em>", "<strong>"],
    correctAnswer: "<strong>",
  },
  {
    id: 34,
    technology: "html",
    level: "Intermediate",
    question: "What is the correct HTML for referring to an external style sheet?",
    options: ["<style src='mystyle.css'>", "<link rel='stylesheet' type='text/css' href='mystyle.css'>", "<stylesheet>mystyle.css</stylesheet>", "<link href='mystyle.css'>"],
    correctAnswer: "<link rel='stylesheet' type='text/css' href='mystyle.css'>",
  },
  {
    id: 35,
    technology: "html",
    level: "Intermediate",
    question: "Which attribute specifies an input field must be filled out?",
    options: ["validate", "required", "placeholder", "mandatory"],
    correctAnswer: "required",
  },
  {
    id: 36,
    technology: "html",
    level: "Intermediate",
    question: "What is the purpose of the HTML <figure> and <figcaption> elements?",
    options: ["To define a table with a caption", "To embed a video with a title", "To group media content with a caption", "To create a form with labels"],
    correctAnswer: "To group media content with a caption",
  },
  {
    id: 37,
    technology: "html",
    level: "Intermediate",
    question: "Which tag is used to embed an SVG image directly into an HTML page?",
    options: ["<img>", "<svg>", "<object>", "<embed>"],
    correctAnswer: "<svg>",
  },
  {
    id: 38,
    technology: "html",
    level: "Intermediate",
    question: "What does the 'defer' attribute in a <script> tag do?",
    options: ["Pauses HTML parsing until script loads", "Executes the script immediately", "Delays script execution until HTML is parsed", "Makes the script run in the background"],
    correctAnswer: "Delays script execution until HTML is parsed",
  },
  // HTML - Pro
  {
    id: 39,
    technology: "html",
    level: "Pro",
    question: "Explain the difference between <div> and <section> semantic elements.",
    options: [
      "No difference, they are interchangeable",
      "<div> is for generic grouping, <section> for thematic grouping of content",
      "<section> is deprecated, <div> is preferred",
      "<div> is for layout, <section> is for content specific styling",
    ],
    correctAnswer: "<div> is for generic grouping, <section> for thematic grouping of content",
  },
  {
    id: 40,
    technology: "html",
    level: "Pro",
    question: "What is the purpose of the 'srcset' attribute in the <img> tag?",
    options: [
      "To provide a fallback image",
      "To define image dimensions",
      "To provide different image sources for different screen sizes/resolutions",
      "To lazy load images",
    ],
    correctAnswer: "To provide different image sources for different screen sizes/resolutions",
  },
  {
    id: 41,
    technology: "html",
    level: "Pro",
    question: "How do custom data attributes (data-*) work and why are they useful?",
    options: [
      "They are used for defining global styles",
      "They allow storing extra information on standard HTML elements without violating HTML standards",
      "They are specific to server-side rendering",
      "They are used only for form validation",
    ],
    correctAnswer: "They allow storing extra information on standard HTML elements without violating HTML standards",
  },
  {
    id: 42,
    technology: "html",
    level: "Pro",
    question: "What is the purpose of the HTML <template> tag?",
    options: [
      "To define a page layout",
      "To create reusable client-side content that is not rendered on page load",
      "To import external HTML documents",
      "To define a custom element",
    ],
    correctAnswer: "To create reusable client-side content that is not rendered on page load",
  },
  {
    id: 43,
    technology: "html",
    level: "Pro",
    question: "Explain the 'rel' attribute value 'preload' in the <link> tag.",
    options: [
      "It instructs the browser to download the linked resource as a lower priority",
      "It makes the browser immediately fetch a resource that will be needed later",
      "It specifies that the linked resource should be pre-rendered",
      "It defines a relationship between the current document and the linked document",
    ],
    correctAnswer: "It makes the browser immediately fetch a resource that will be needed later",
  },
  {
    id: 44,
    technology: "html",
    level: "Pro",
    question: "What are Web Components and what are their four main specifications?",
    options: [
      "A set of APIs for creating reusable UI components in JavaScript; Shadow DOM, Custom Elements, HTML Templates, HTML Imports",
      "A framework for building single-page applications; React, Angular, Vue, Svelte",
      "A way to optimize image loading; JPEG, PNG, GIF, WebP",
      "A method for structuring CSS; BEM, OOCSS, SMACSS, ITCSS",
    ],
    correctAnswer: "A set of APIs for creating reusable UI components in JavaScript; Shadow DOM, Custom Elements, HTML Templates, HTML Imports",
  },
  {
    id: 45,
    technology: "html",
    level: "Pro",
    question: "Describe the concept of 'semantic HTML'.",
    options: [
      "Using HTML tags for styling purposes",
      "Writing HTML code that is easy to understand by humans",
      "Using HTML tags that clearly describe the meaning of the content they contain",
      "HTML that is designed for search engine optimization only",
    ],
    correctAnswer: "Using HTML tags that clearly describe the meaning of the content they contain",
  },
  {
    id: 46,
    technology: "html",
    level: "Pro",
    question: "What is the 'async' attribute in a <script> tag used for?",
    options: [
      "To load the script synchronously",
      "To ensure the script runs after all other scripts",
      "To execute the script asynchronously without blocking HTML parsing, but not necessarily in order",
      "To defer the script execution until the DOM is fully loaded",
    ],
    correctAnswer: "To execute the script asynchronously without blocking HTML parsing, but not necessarily in order",
  },
  {
    id: 47,
    technology: "html",
    level: "Pro",
    question: "How do you implement accessible navigation for screen readers?",
    options: [
      "By using only <div> tags for navigation",
      "By hiding navigation links with CSS",
      "By using semantic <nav> tags, ARIA attributes, and clear link text",
      "By relying solely on JavaScript for navigation",
    ],
    correctAnswer: "By using semantic <nav> tags, ARIA attributes, and clear link text",
  },
  {
    id: 48,
    technology: "html",
    level: "Pro",
    question: "What is the purpose of the 'crossorigin' attribute in HTML elements like <img> or <script>?",
    options: [
      "To specify the image's orientation",
      "To enable Cross-Origin Resource Sharing (CORS) for fetching resources from different origins",
      "To define the script's execution environment",
      "To prevent hotlinking of images",
    ],
    correctAnswer: "To enable Cross-Origin Resource Sharing (CORS) for fetching resources from different origins",
  },

  // ================= CSS =================
  {
    id: 4,
    technology: "css",
    level: "Beginner",
    question: "What does CSS stand for?",
    options: [
      "Colorful Style Sheets",
      "Creative Style Sheets",
      "Cascading Style Sheets",
      "Computer Style Sheets",
    ],
    correctAnswer: "Cascading Style Sheets",
  },
  {
    id: 5,
    technology: "css",
    level: "Intermediate",
    question: "Which property controls space outside an element?",
    options: ["padding", "margin", "border", "gap"],
    correctAnswer: "margin",
  },
  {
    id: 6,
    technology: "css",
    level: "Pro",
    question: "Which layout system is best for 2D layouts?",
    options: ["Flexbox", "Grid", "Float", "Position"],
    correctAnswer: "Grid",
  },
  // CSS - Beginner
  {
    id: 49,
    technology: "css",
    level: "Beginner",
    question: "Which CSS property is used to change the text color of an element?",
    options: ["background-color", "text-color", "color", "font-color"],
    correctAnswer: "color",
  },
  {
    id: 50,
    technology: "css",
    level: "Beginner",
    question: "Which property is used to change the background color?",
    options: ["bgcolor", "color", "background-color", "background"],
    correctAnswer: "background-color",
  },
  {
    id: 51,
    technology: "css",
    level: "Beginner",
    question: "How do you add a background image in CSS?",
    options: ["background-image: 'image.png';", "background: url('image.png');", "img: url('image.png');", "background-url: 'image.png';"],
    correctAnswer: "background: url('image.png');",
  },
  {
    id: 52,
    technology: "css",
    level: "Beginner",
    question: "Which CSS property controls the text size?",
    options: ["font-style", "text-size", "font-size", "text-style"],
    correctAnswer: "font-size",
  },
  {
    id: 53,
    technology: "css",
    level: "Beginner",
    question: "What is the correct CSS syntax for making all <p> elements bold?",
    options: ["p {text-size: bold;}", "p {font-weight: bold;}", "p {bold: true;}", "p {font: bold;}"],
    correctAnswer: "p {font-weight: bold;}",
  },
  {
    id: 54,
    technology: "css",
    level: "Beginner",
    question: "How do you center text in CSS?",
    options: ["align-text: center;", "text-align: center;", "center-text: true;", "text-position: center;"],
    correctAnswer: "text-align: center;",
  },
  {
    id: 55,
    technology: "css",
    level: "Beginner",
    question: "Which property is used to change the font of an element?",
    options: ["font-family", "font-name", "font-style", "typeface"],
    correctAnswer: "font-family",
  },
  {
    id: 56,
    technology: "css",
    level: "Beginner",
    question: "What is the universal selector in CSS?",
    options: ["#", ".", "*", "@"],
    correctAnswer: "*",
  },
  {
    id: 57,
    technology: "css",
    level: "Beginner",
    question: "Which CSS property is used to add space between the element's border and its content?",
    options: ["margin", "spacing", "padding", "border-spacing"],
    correctAnswer: "padding",
  },
  {
    id: 58,
    technology: "css",
    level: "Beginner",
    question: "How do you select an element with id 'demo'?",
    options: [".demo", "demo", "#demo", "*demo"],
    correctAnswer: "#demo",
  },
  // CSS - Intermediate
  {
    id: 59,
    technology: "css",
    level: "Intermediate",
    question: "What is the 'box model' in CSS?",
    options: [
      "A model for arranging elements in 3D space",
      "A box that wraps around every HTML element, consisting of: margins, borders, padding, and the actual content",
      "A method for calculating element dimensions",
      "A way to align items in a flex container",
    ],
    correctAnswer: "A box that wraps around every HTML element, consisting of: margins, borders, padding, and the actual content",
  },
  {
    id: 60,
    technology: "css",
    level: "Intermediate",
    question: "Explain the difference between 'display: block;' and 'display: inline;'",
    options: [
      "Block elements take up full width, inline elements only take up necessary width",
      "Inline elements can have height and width, block elements cannot",
      "Block elements cannot have margin or padding, inline elements can",
      "No real difference, depends on browser",
    ],
    correctAnswer: "Block elements take up full width, inline elements only take up necessary width",
  },
  {
    id: 61,
    technology: "css",
    level: "Intermediate",
    question: "What is the purpose of the 'z-index' property?",
    options: [
      "To control text alignment",
      "To specify the stack order of an element (which element should be placed in front of, or behind, others)",
      "To set the width of an element",
      "To animate elements in 3D",
    ],
    correctAnswer: "To specify the stack order of an element (which element should be placed in front of, or behind, others)",
  },
  {
    id: 62,
    technology: "css",
    level: "Intermediate",
    question: "What are pseudo-classes in CSS?",
    options: [
      "Classes used only for JavaScript",
      "Keywords added to selectors to specify a special state of the element",
      "Classes that only apply to parent elements",
      "Styles that are not supported by all browsers",
    ],
    correctAnswer: "Keywords added to selectors to specify a special state of the element",
  },
  {
    id: 63,
    technology: "css",
    level: "Intermediate",
    question: "How does 'position: relative;' differ from 'position: absolute;'?",
    options: [
      "Relative positions relative to its normal position, absolute positions relative to its nearest positioned ancestor",
      "Absolute always positions relative to the body, relative positions to the parent",
      "Relative is for 2D, absolute is for 3D",
      "There is no practical difference",
    ],
    correctAnswer: "Relative positions relative to its normal position, absolute positions relative to its nearest positioned ancestor",
  },
  {
    id: 64,
    technology: "css",
    level: "Intermediate",
    question: "What is the 'float' property used for?",
    options: [
      "To move an element up or down",
      "To wrap text around images",
      "To position elements horizontally",
      "To create animations",
    ],
    correctAnswer: "To position elements horizontally",
  },
  {
    id: 65,
    technology: "css",
    level: "Intermediate",
    question: "What is the difference between 'em' and 'rem' units?",
    options: [
      "em is relative to the parent element's font-size, rem is relative to the root element's font-size",
      "rem is relative to the parent element's font-size, em is relative to the root element's font-size",
      "em is a fixed unit, rem is a relative unit",
      "They are interchangeable",
    ],
    correctAnswer: "em is relative to the parent element's font-size, rem is relative to the root element's font-size",
  },
  {
    id: 66,
    technology: "css",
    level: "Intermediate",
    question: "How do you create a responsive design using media queries?",
    options: [
      "By using JavaScript to detect screen size",
      "By applying different styles based on device width or characteristics",
      "By using only fluid layouts",
      "By declaring all styles inline",
    ],
    correctAnswer: "By applying different styles based on device width or characteristics",
  },
  {
    id: 67,
    technology: "css",
    level: "Intermediate",
    question: "What is the 'overflow' property used for?",
    options: [
      "To control how extra content is handled when it overflows an element's box",
      "To create scrolling animations",
      "To adjust element spacing",
      "To make elements visible outside their container",
    ],
    correctAnswer: "To control how extra content is handled when it overflows an element's box",
  },
  {
    id: 68,
    technology: "css",
    level: "Intermediate",
    question: "What is a CSS reset and why is it used?",
    options: [
      "To clear all browser cache",
      "To reset all CSS properties to their default browser values",
      "To remove all default browser styling, providing a consistent baseline for styling",
      "To optimize CSS file size",
    ],
    correctAnswer: "To remove all default browser styling, providing a consistent baseline for styling",
  },
  // CSS - Pro
  {
    id: 69,
    technology: "css",
    level: "Pro",
    question: "Explain the concept of 'BEM' methodology in CSS.",
    options: [
      "A way to organize CSS files alphabetically",
      "A naming convention for classes: Block, Element, Modifier, to make CSS more modular and reusable",
      "A CSS preprocessor",
      "A method for optimizing CSS loading performance",
    ],
    correctAnswer: "A naming convention for classes: Block, Element, Modifier, to make CSS more modular and reusable",
  },
  {
    id: 70,
    technology: "css",
    level: "Pro",
    question: "Describe the differences between 'justify-content' and 'align-items' in Flexbox.",
    options: [
      "justify-content aligns items along the cross-axis, align-items aligns along the main-axis",
      "justify-content aligns items along the main-axis, align-items aligns along the cross-axis",
      "Both properties do the same thing",
      "justify-content is for Grid, align-items is for Flexbox",
    ],
    correctAnswer: "justify-content aligns items along the main-axis, align-items aligns along the cross-axis",
  },
  {
    id: 71,
    technology: "css",
    level: "Pro",
    question: "What is the purpose of 'CSS Variables' (Custom Properties)? Provide an example.",
    options: [
      "They are placeholders for JavaScript values",
      "They allow defining reusable values (like colors or font sizes) in CSS, making stylesheets easier to maintain. Example: :root { --primary-color: blue; }",
      "They are used for conditional styling",
      "They are global CSS selectors",
    ],
    correctAnswer: "They allow defining reusable values (like colors or font sizes) in CSS, making stylesheets easier to maintain. Example: :root { --primary-color: blue; }",
  },
  {
    id: 72,
    technology: "css",
    level: "Pro",
    question: "Explain the concept of 'specificity' in CSS.",
    options: [
      "How specific a color value is",
      "The algorithm browsers use to determine which CSS rule applies to an element when multiple rules could apply",
      "How unique a selector is",
      "The order in which CSS properties are declared",
    ],
    correctAnswer: "The algorithm browsers use to determine which CSS rule applies to an element when multiple rules could apply",
  },
  {
    id: 73,
    technology: "css",
    level: "Pro",
    question: "What is the difference between 'grid-template-columns' and 'grid-auto-columns'?",
    options: [
      "grid-template-columns defines explicit column tracks, grid-auto-columns defines the size of implicitly created column tracks",
      "They are both used for defining row sizes",
      "grid-auto-columns is deprecated",
      "grid-template-columns is for responsive design, grid-auto-columns is for fixed layouts",
    ],
    correctAnswer: "grid-template-columns defines explicit column tracks, grid-auto-columns defines the size of implicitly created column tracks",
  },
  {
    id: 74,
    technology: "css",
    level: "Pro",
    question: "Describe how to implement a 'sticky' footer using CSS.",
    options: [
      "Using `position: fixed`",
      "By setting `min-height: 100vh` on the body and using flexbox or grid to push the footer to the bottom",
      "Using `float: right` on the footer",
      "By only using JavaScript to position the footer",
    ],
    correctAnswer: "By setting `min-height: 100vh` on the body and using flexbox or grid to push the footer to the bottom",
  },
  {
    id: 75,
    technology: "css",
    level: "Pro",
    question: "What are CSS pseudo-elements and how are they useful?",
    options: [
      "Elements that don't exist in the HTML",
      "Used to style specified parts of an element, e.g., ::before, ::after for adding decorative content",
      "Elements that are only visible on certain devices",
      "A way to define custom HTML elements",
    ],
    correctAnswer: "Used to style specified parts of an element, e.g., ::before, ::after for adding decorative content",
  },
  {
    id: 76,
    technology: "css",
    level: "Pro",
    question: "Explain the concept of 'viewport units' (vw, vh, vmin, vmax).",
    options: [
      "Units relative to the parent element's size",
      "Units relative to the font size of the root element",
      "Units relative to the size of the viewport: vw (viewport width), vh (viewport height), vmin (minimum of vw/vh), vmax (maximum of vw/vh)",
      "Units used only for print stylesheets",
    ],
    correctAnswer: "Units relative to the size of the viewport: vw (viewport width), vh (viewport height), vmin (minimum of vw/vh), vmax (maximum of vw/vh)",
  },
  {
    id: 77,
    technology: "css",
    level: "Pro",
    question: "What is the role of 'contain' property in CSS?",
    options: [
      "To prevent elements from overlapping",
      "To isolate a part of the DOM from the rest of the document, preventing its content from affecting other elements",
      "To contain fluid images within their parent",
      "To control the display of block-level elements",
    ],
    correctAnswer: "To isolate a part of the DOM from the rest of the document, preventing its content from affecting other elements",
  },
  {
    id: 78,
    technology: "css",
    level: "Pro",
    question: "How do you optimize CSS for performance?",
    options: [
      "By writing all CSS inline",
      "By using external stylesheets, minimizing HTTP requests, minifying CSS, using efficient selectors, and avoiding expensive properties",
      "By adding !important to every rule",
      "By only using JavaScript to style elements",
    ],
    correctAnswer: "By using external stylesheets, minimizing HTTP requests, minifying CSS, using efficient selectors, and avoiding expensive properties",
  },

  // ================= JavaScript =================
  {
    id: 7,
    technology: "js",
    level: "Beginner",
    question: "Which keyword is used to declare a variable?",
    options: ["int", "var", "define", "letvar"],
    correctAnswer: "var",
  },
  {
    id: 8,
    technology: "js",
    level: "Intermediate",
    question: "What does Array.map() return?",
    options: ["Single value", "Boolean", "New array", "Object"],
    correctAnswer: "New array",
  },
  {
    id: 9,
    technology: "js",
    level: "Pro",
    question: "What is a closure?",
    options: [
      "Function inside loop",
      "Function with preserved lexical scope",
      "Callback function",
      "Async function",
    ],
    correctAnswer: "Function with preserved lexical scope",
  },
  // JS - Beginner
  {
    id: 79,
    technology: "js",
    level: "Beginner",
    question: "How do you write 'Hello World' in an alert box?",
    options: ["msg('Hello World');", "alertBox('Hello World');", "alert('Hello World');", "msgBox('Hello World');"],
    correctAnswer: "alert('Hello World');",
  },
  {
    id: 80,
    technology: "js",
    level: "Beginner",
    question: "Where is the correct place to insert a JavaScript?",
    options: ["The <head> section", "The <body> section", "Both the <head> section and the <body> section are correct", "The <footer> section"],
    correctAnswer: "Both the <head> section and the <body> section are correct",
  },
  {
    id: 81,
    technology: "js",
    level: "Beginner",
    question: "How do you call a function named 'myFunction'?",
    options: ["call myFunction();", "myFunction();", "call function myFunction();", "run myFunction();"],
    correctAnswer: "myFunction();",
  },
  {
    id: 82,
    technology: "js",
    level: "Beginner",
    question: "How do you write an IF statement in JavaScript?",
    options: ["if i = 5 then", "if i == 5", "if (i == 5)", "if i = 5"],
    correctAnswer: "if (i == 5)",
  },
  {
    id: 83,
    technology: "js",
    level: "Beginner",
    question: "Which operator is used to assign a value to a variable?",
    options: ["*", "x", "=", "-"],
    correctAnswer: "=",
  },
  {
    id: 84,
    technology: "js",
    level: "Beginner",
    question: "What is the correct way to write a JavaScript array?",
    options: ["var colors = (1:'red', 2:'green', 3:'blue')", "var colors = ['red', 'green', 'blue']", "var colors = 'red', 'green', 'blue'", "var colors = 1 = ('red'), 2 = ('green'), 3 = ('blue')"],
    correctAnswer: "var colors = ['red', 'green', 'blue']",
  },
  {
    id: 85,
    technology: "js",
    level: "Beginner",
    question: "How do you round the number 7.25 to the nearest integer?",
    options: ["Math.rnd(7.25)", "round(7.25)", "Math.round(7.25)", "Math.floor(7.25)"],
    correctAnswer: "Math.round(7.25)",
  },
  {
    id: 86,
    technology: "js",
    level: "Beginner",
    question: "Which event occurs when the user clicks on an HTML element?",
    options: ["onchange", "onmouseclick", "onclick", "onmouseover"],
    correctAnswer: "onclick",
  },
  {
    id: 87,
    technology: "js",
    level: "Beginner",
    question: "How do you declare a JavaScript variable?",
    options: ["variable carName;", "var carName;", "v carName;", "string carName;"],
    correctAnswer: "var carName;",
  },
  {
    id: 88,
    technology: "js",
    level: "Beginner",
    question: "Which of the following is a way to create an object in JavaScript?",
    options: ["new Object();", "{};", "Object.create();", "All of the above"],
    correctAnswer: "All of the above",
  },
  // JS - Intermediate
  {
    id: 89,
    technology: "js",
    level: "Intermediate",
    question: "What is the difference between '==' and '==='?",
    options: [
      "== compares value, === compares value and type",
      "== compares type, === compares value",
      "No difference, they are interchangeable",
      "=== is for numbers, == is for strings",
    ],
    correctAnswer: "== compares value, === compares value and type",
  },
  {
    id: 90,
    technology: "js",
    level: "Intermediate",
    question: "What is an 'event bubbling' in JavaScript?",
    options: [
      "When an event handler is not triggered",
      "When an event propagates from the target element up to the document root",
      "When an event is cancelled",
      "When multiple events occur at the same time",
    ],
    correctAnswer: "When an event propagates from the target element up to the document root",
  },
  {
    id: 91,
    technology: "js",
    level: "Intermediate",
    question: "What is 'hoisting' in JavaScript?",
    options: [
      "A way to optimize code execution",
      "The process of moving all declarations to the top of the current scope (to the top of the current script or the current function)",
      "A method for asynchronous operations",
      "A type of error handling",
    ],
    correctAnswer: "The process of moving all declarations to the top of the current scope (to the top of the current script or the current function)",
  },
  {
    id: 92,
    technology: "js",
    level: "Intermediate",
    question: "What is a 'callback function' in JavaScript?",
    options: [
      "A function that calls itself",
      "A function passed into another function as an argument, which is then invoked inside the outer function to complete some kind of routine or action",
      "A function that returns a callback",
      "A function used only for error handling",
    ],
    correctAnswer: "A function passed into another function as an argument, which is then invoked inside the outer function to complete some kind of routine or action",
  },
  {
    id: 93,
    technology: "js",
    level: "Intermediate",
    question: "What is the purpose of the 'this' keyword in JavaScript?",
    options: [
      "It refers to the previous function call",
      "It refers to the current function's scope",
      "It refers to the object it belongs to",
      "It refers to the global window object",
    ],
    correctAnswer: "It refers to the object it belongs to",
  },
  {
    id: 94,
    technology: "js",
    level: "Intermediate",
    question: "Explain 'scope' in JavaScript.",
    options: [
      "The visual boundaries of an element",
      "The accessibility of variables, functions, and objects in some particular part of your code during runtime",
      "The order of execution of functions",
      "The performance of a function",
    ],
    correctAnswer: "The accessibility of variables, functions, and objects in some particular part of your code during runtime",
  },
  {
    id: 95,
    technology: "js",
    level: "Intermediate",
    question: "What are 'arrow functions' and how do they differ from regular functions?",
    options: [
      "They are functions that use arrows for syntax, and they have their own 'this' binding",
      "They are a shorter syntax for writing function expressions, and they do not have their own 'this' binding (they inherit 'this' from the enclosing lexical context)",
      "They are only used for asynchronous operations",
      "They are a type of constructor function",
    ],
    correctAnswer: "They are a shorter syntax for writing function expressions, and they do not have their own 'this' binding (they inherit 'this' from the enclosing lexical context)",
  },
  {
    id: 96,
    technology: "js",
    level: "Intermediate",
    question: "What is the purpose of 'localStorage' and 'sessionStorage'?",
    options: [
      "They are used for server-side data storage",
      "They are types of JavaScript variables",
      "They allow web applications to store data locally within the user's browser, with localStorage persisting across sessions and sessionStorage only for the duration of the page session",
      "They are methods for manipulating the DOM",
    ],
    correctAnswer: "They allow web applications to store data locally within the user's browser, with localStorage persisting across sessions and sessionStorage only for the duration of the page session",
  },
  {
    id: 97,
    technology: "js",
    level: "Intermediate",
    question: "What does the 'typeof' operator do?",
    options: [
      "Returns a boolean indicating if a variable is defined",
      "Returns the data type of a variable",
      "Returns the value of a variable",
      "Checks if a variable is an object",
    ],
    correctAnswer: "Returns the data type of a variable",
  },
  {
    id: 98,
    technology: "js",
    level: "Intermediate",
    question: "Explain the concept of 'event delegation'.",
    options: [
      "Assigning multiple event listeners to a single element",
      "Attaching a single event listener to a parent element to manage events for its children, reducing memory usage and simplifying code",
      "Delegating event handling to a separate JavaScript file",
      "Ignoring certain events to improve performance",
    ],
    correctAnswer: "Attaching a single event listener to a parent element to manage events for its children, reducing memory usage and simplifying code",
  },
  // JS - Pro
  {
    id: 99,
    technology: "js",
    level: "Pro",
    question: "What are 'Promises' in JavaScript and why are they used?",
    options: [
      "A way to handle synchronous operations",
      "Objects representing the eventual completion or failure of an asynchronous operation, used to avoid callback hell",
      "A type of data structure",
      "A method for global variable declaration",
    ],
    correctAnswer: "Objects representing the eventual completion or failure of an asynchronous operation, used to avoid callback hell",
  },
  {
    id: 100,
    technology: "js",
    level: "Pro",
    question: "Explain 'event loop' in JavaScript.",
    options: [
      "A loop that continuously checks for new events",
      "The mechanism that JavaScript uses to handle asynchronous operations, allowing non-blocking I/O operations",
      "A way to prevent infinite loops",
      "A deprecated feature of JavaScript",
    ],
    correctAnswer: "The mechanism that JavaScript uses to handle asynchronous operations, allowing non-blocking I/O operations",
  },
  {
    id: 101,
    technology: "js",
    level: "Pro",
    question: "What is 'prototypal inheritance' in JavaScript?",
    options: [
      "A class-based inheritance model",
      "A way for objects to inherit properties and methods from other objects (their prototypes)",
      "A type of error handling mechanism",
      "A method for asynchronous programming",
    ],
    correctAnswer: "A way for objects to inherit properties and methods from other objects (their prototypes)",
  },
  {
    id: 102,
    technology: "js",
    level: "Pro",
    question: "Describe 'throttle' and 'debounce' functions.",
    options: [
      "They are used for styling elements",
      "Techniques to control how often a function is executed: throttle limits execution to a specified interval, debounce delays execution until a certain time has passed without any further calls",
      "Methods for optimizing image loading",
      "Types of JavaScript frameworks",
    ],
    correctAnswer: "Techniques to control how often a function is executed: throttle limits execution to a specified interval, debounce delays execution until a certain time has passed without any further calls",
  },
  {
    id: 103,
    technology: "js",
    level: "Pro",
    question: "What is the difference between 'let', 'const', and 'var'?",
    options: [
      "No real difference, all declare variables",
      "var is function-scoped and can be re-declared; let and const are block-scoped. let can be re-assigned, const cannot.",
      "const is for constants, let is for variables, var is deprecated",
      "let and const are hoisted, var is not",
    ],
    correctAnswer: "var is function-scoped and can be re-declared; let and const are block-scoped. let can be re-assigned, const cannot.",
  },
  {
    id: 104,
    technology: "js",
    level: "Pro",
    question: "Explain 'async/await' and how they improve asynchronous code.",
    options: [
      "Syntax for writing synchronous code",
      "Syntactic sugar built on Promises, making asynchronous code look and behave more like synchronous code, improving readability and error handling",
      "Methods for parallel processing",
      "Used for blocking operations",
    ],
    correctAnswer: "Syntactic sugar built on Promises, making asynchronous code look and behave more like synchronous code, improving readability and error handling",
  },
  {
    id: 105,
    technology: "js",
    level: "Pro",
    question: "What is a 'Generator function' in JavaScript?",
    options: [
      "A function that generates random numbers",
      "A function that can be paused and resumed, producing a sequence of values over time using the 'yield' keyword",
      "A function that creates other functions",
      "A function used for debugging purposes",
    ],
    correctAnswer: "A function that can be paused and resumed, producing a sequence of values over time using the 'yield' keyword",
  },
  {
    id: 106,
    technology: "js",
    level: "Pro",
    question: "What is 'Strict Mode' in JavaScript and its benefits?",
    options: [
      "A mode that compiles JavaScript code faster",
      "A way to write less code",
      "A feature that enables a stricter parsing and error handling, helping write 'safer' JavaScript and catch common coding errors",
      "A mode for running JavaScript only on the server",
    ],
    correctAnswer: "A feature that enables a stricter parsing and error handling, helping write 'safer' JavaScript and catch common coding errors",
  },
  {
    id: 107,
    technology: "js",
    level: "Pro",
    question: "Explain the 'Proxy' object in JavaScript.",
    options: [
      "A way to create secure network requests",
      "An object that allows you to intercept and customize operations for another object (target), such as property lookup, assignment, enumeration, function invocation, etc.",
      "A method for deep cloning objects",
      "A deprecated feature for browser compatibility",
    ],
    correctAnswer: "An object that allows you to intercept and customize operations for another object (target), such as property lookup, assignment, enumeration, function invocation, etc.",
  },
  {
    id: 108,
    technology: "js",
    level: "Pro",
    question: "What is 'WebAssembly' and its relationship with JavaScript?",
    options: [
      "A new version of JavaScript",
      "A binary instruction format for a stack-based virtual machine, providing a way to run code written in languages other than JavaScript in web browsers at near-native speed, complementing JavaScript",
      "A JavaScript framework for embedded systems",
      "A tool for debugging JavaScript applications",
    ],
    correctAnswer: "A binary instruction format for a stack-based virtual machine, providing a way to run code written in languages other than JavaScript in web browsers at near-native speed, complementing JavaScript",
  },

  // ================= React =================
  {
    id: 10,
    technology: "react",
    level: "Beginner",
    question: "Which hook is used to manage state?",
    options: ["useEffect", "useRef", "useState", "useMemo"],
    correctAnswer: "useState",
  },
  {
    id: 11,
    technology: "react",
    level: "Intermediate",
    question: "Why are keys important in lists?",
    options: [
      "For styling",
      "For SEO",
      "To uniquely identify elements",
      "To sort items",
    ],
    correctAnswer: "To uniquely identify elements",
  },
  {
    id: 12,
    technology: "react",
    level: "Pro",
    question: "What does React Fiber optimize?",
    options: [
      "Styling",
      "Routing",
      "Rendering and reconciliation",
      "State storage",
    ],
    correctAnswer: "Rendering and reconciliation",
  },
  // React - Beginner
  {
    id: 109,
    technology: "react",
    level: "Beginner",
    question: "What is JSX in React?",
    options: [
      "A JavaScript library for UI",
      "A syntax extension that allows writing HTML-like code in JavaScript",
      "A state management tool",
      "A CSS preprocessor",
    ],
    correctAnswer: "A syntax extension that allows writing HTML-like code in JavaScript",
  },
  {
    id: 110,
    technology: "react",
    level: "Beginner",
    question: "How do you create a functional component in React?",
    options: [
      "class MyComponent extends React.Component {}",
      "function MyComponent() {}",
      "const MyComponent = new Component();",
      "React.createFunction()",
    ],
    correctAnswer: "function MyComponent() {}",
  },
  {
    id: 111,
    technology: "react",
    level: "Beginner",
    question: "What is 'props' in React?",
    options: [
      "Internal component state",
      "Arguments passed into React components",
      "A method to update the DOM directly",
      "A built-in React hook",
    ],
    correctAnswer: "Arguments passed into React components",
  },
  {
    id: 112,
    technology: "react",
    level: "Beginner",
    question: "What is the virtual DOM in React?",
    options: [
      "A direct manipulation of the browser DOM",
      "A copy of the actual DOM, kept in memory, for efficient updates",
      "A way to write CSS in React",
      "A server-side rendering technique",
    ],
    correctAnswer: "A copy of the actual DOM, kept in memory, for efficient updates",
  },
  {
    id: 113,
    technology: "react",
    level: "Beginner",
    question: "How do you render a React component to the DOM?",
    options: [
      "ReactDOM.render(<App />, document.getElementById('root'));",
      "App.renderToDom();",
      "document.attachComponent(<App />);",
      "React.display(<App />);",
    ],
    correctAnswer: "ReactDOM.render(<App />, document.getElementById('root'));",
  },
  {
    id: 114,
    technology: "react",
    level: "Beginner",
    question: "Which command creates a new React app?",
    options: [
      "npm start react-app",
      "npx create-react-app my-app",
      "react create-app my-app",
      "npm build react-app",
    ],
    correctAnswer: "npx create-react-app my-app",
  },
  {
    id: 115,
    technology: "react",
    level: "Beginner",
    question: "What are 'components' in React?",
    options: [
      "HTML elements",
      "Functions or classes that return React elements, representing a part of the UI",
      "JavaScript variables",
      "CSS styles",
    ],
    correctAnswer: "Functions or classes that return React elements, representing a part of the UI",
  },
  {
    id: 116,
    technology: "react",
    level: "Beginner",
    question: "What is the purpose of 'state' in React?",
    options: [
      "To store external data",
      "To manage data that can change over time within a component",
      "To define global variables",
      "To handle server-side logic",
    ],
    correctAnswer: "To manage data that can change over time within a component",
  },
  {
    id: 117,
    technology: "react",
    level: "Beginner",
    question: "How do you handle events in React (e.g., a button click)?",
    options: [
      "Using inline HTML event attributes (onclick='doSomething()')",
      "By attaching event listeners directly to the DOM in JavaScript",
      "By defining event handler functions as props to elements (e.g., onClick={handleClick})",
      "React handles all events automatically",
    ],
    correctAnswer: "By defining event handler functions as props to elements (e.g., onClick={handleClick})",
  },
  {
    id: 118,
    technology: "react",
    level: "Beginner",
    question: "What is the typical entry point file for a React application?",
    options: ["app.js", "index.html", "main.js", "index.js"],
    correctAnswer: "index.js",
  },
  // React - Intermediate
  {
    id: 119,
    technology: "react",
    level: "Intermediate",
    question: "Explain the 'useEffect' hook.",
    options: [
      "Used for defining component styling",
      "Used for performing side effects in functional components (like data fetching, subscriptions, or manually changing the DOM)",
      "Used for managing global state",
      "Used only for animations",
    ],
    correctAnswer: "Used for performing side effects in functional components (like data fetching, subscriptions, or manually changing the DOM)",
  },
  {
    id: 120,
    technology: "react",
    level: "Intermediate",
    question: "What is 'Conditional Rendering' in React?",
    options: [
      "Rendering components only if a certain condition is met",
      "Rendering components based on user input",
      "Rendering components on the server-side",
      "Rendering components asynchronously",
    ],
    correctAnswer: "Rendering components only if a certain condition is met",
  },
  {
    id: 121,
    technology: "react",
    level: "Intermediate",
    question: "What is 'lifting state up' in React?",
    options: [
      "Moving state from a child component to a parent component to share it among siblings",
      "Moving state from a parent to a child",
      "Using a global state management library",
      "Optimizing state updates for performance",
    ],
    correctAnswer: "Moving state from a child component to a parent component to share it among siblings",
  },
  {
    id: 122,
    technology: "react",
    level: "Intermediate",
    question: "Explain the purpose of 'React Router'.",
    options: [
      "To handle network requests",
      "To manage application state",
      "To handle navigation and routing in a single-page application",
      "To style components dynamically",
    ],
    correctAnswer: "To handle navigation and routing in a single-page application",
  },
  {
    id: 123,
    technology: "react",
    level: "Intermediate",
    question: "What is the 'Context API' in React?",
    options: [
      "A way to pass props deeply without manually passing them through every level of the component tree",
      "A method for managing component lifecycle",
      "A tool for creating global variables",
      "A replacement for Redux",
    ],
    correctAnswer: "A way to pass props deeply without manually passing them through every level of the component tree",
  },
  {
    id: 124,
    technology: "react",
    level: "Intermediate",
    question: "What are 'Higher-Order Components' (HOCs)?",
    options: [
      "Components that are rendered at a higher level in the DOM tree",
      "Functions that take a component and return a new component with enhanced functionality",
      "Components that have a higher priority in rendering",
      "React's built-in components",
    ],
    correctAnswer: "Functions that take a component and return a new component with enhanced functionality",
  },
  {
    id: 125,
    technology: "react",
    level: "Intermediate",
    question: "What is the 'useRef' hook used for?",
    options: [
      "To create mutable ref objects that persist across renders, often used to access DOM elements directly",
      "To store immutable data",
      "To manage component state",
      "To optimize rendering performance",
    ],
    correctAnswer: "To create mutable ref objects that persist across renders, often used to access DOM elements directly",
  },
  {
    id: 126,
    technology: "react",
    level: "Intermediate",
    question: "Explain the concept of 'controlled components' in React forms.",
    options: [
      "Components whose state is controlled by the DOM",
      "Form elements whose values are controlled by React state, requiring explicit handling of input changes",
      "Components that are rendered conditionally",
      "Components that only accept specific props",
    ],
    correctAnswer: "Form elements whose values are controlled by React state, requiring explicit handling of input changes",
  },
  {
    id: 127,
    technology: "react",
    level: "Intermediate",
    question: "What is the purpose of 'React.memo'?",
    options: [
      "To store data in local storage",
      "To prevent re-rendering of functional components if their props haven't changed, optimizing performance",
      "To create memoized functions",
      "To manage complex state logic",
    ],
    correctAnswer: "To prevent re-rendering of functional components if their props haven't changed, optimizing performance",
  },
  {
    id: 128,
    technology: "react",
    level: "Intermediate",
    question: "How do you fetch data in React using hooks?",
    options: [
      "Using `componentDidMount` lifecycle method",
      "Using the `useEffect` hook, often with `fetch` or `axios` inside",
      "Directly in the render method",
      "Using Redux Sagas",
    ],
    correctAnswer: "Using the `useEffect` hook, often with `fetch` or `axios` inside",
  },
  // React - Pro
  {
    id: 129,
    technology: "react",
    level: "Pro",
    question: "Explain 'React Reconciliation' and 'Virtual DOM Diffing'.",
    options: [
      "A process of comparing two React components to see if they are the same",
      "The process React uses to update the actual DOM by comparing the new Virtual DOM tree with the previous one, and only updating the necessary parts of the real DOM",
      "A way to prevent re-renders",
      "A method for managing component state",
    ],
    correctAnswer: "The process React uses to update the actual DOM by comparing the new Virtual DOM tree with the previous one, and only updating the necessary parts of the real DOM",
  },
  {
    id: 130,
    technology: "react",
    level: "Pro",
    question: "What is the 'Suspense' component used for in React?",
    options: [
      "To handle errors in components",
      "To display fallback content while components (or their data) are loading asynchronously",
      "To prevent components from rendering",
      "To perform server-side rendering",
    ],
    correctAnswer: "To display fallback content while components (or their data) are loading asynchronously",
  },
  {
    id: 131,
    technology: "react",
    level: "Pro",
    question: "Describe 'Server-Side Rendering (SSR)' in React and its benefits.",
    options: [
      "Rendering React components only on the client-side",
      "Rendering React components to HTML on the server and sending the pre-rendered HTML to the client, improving initial load performance and SEO",
      "A way to manage global state in React",
      "A technique for optimizing component styling",
    ],
    correctAnswer: "Rendering React components to HTML on the server and sending the pre-rendered HTML to the client, improving initial load performance and SEO",
  },
  {
    id: 132,
    technology: "react",
    level: "Pro",
    question: "What is 'Error Boundary' in React?",
    options: [
      "A way to handle asynchronous errors",
      "A component that catches JavaScript errors anywhere in its child component tree, logs those errors, and displays a fallback UI instead of crashing the entire application",
      "A mechanism to prevent infinite loops",
      "A tool for debugging React applications",
    ],
    correctAnswer: "A component that catches JavaScript errors anywhere in its child component tree, logs those errors, and displays a fallback UI instead of crashing the entire application",
  },
  {
    id: 133,
    technology: "react",
    level: "Pro",
    question: "Explain the 'useReducer' hook and when to use it.",
    options: [
      "Used for simple state management",
      "An alternative to `useState` for managing more complex state logic that involves multiple sub-values or when the next state depends on the previous one, similar to Redux reducers",
      "Used for performing side effects",
      "Used for memoizing values",
    ],
    correctAnswer: "An alternative to `useState` for managing more complex state logic that involves multiple sub-values or when the next state depends on the previous one, similar to Redux reducers",
  },
  {
    id: 134,
    technology: "react",
    level: "Pro",
    question: "What is 'Portals' in React and when would you use them?",
    options: [
      "A way to share state between components",
      "A way to render children into a DOM node that exists outside the DOM hierarchy of the parent component, useful for modals, tooltips, and popovers",
      "A method for routing in React",
      "A feature for creating animations",
    ],
    correctAnswer: "A way to render children into a DOM node that exists outside the DOM hierarchy of the parent component, useful for modals, tooltips, and popovers",
  },
  {
    id: 135,
    technology: "react",
    level: "Pro",
    question: "Describe the concept of 'Immutable State' in React.",
    options: [
      "State that can be directly modified",
      "The practice of not directly modifying state objects or arrays, but instead creating new copies with the desired changes, which helps with performance optimization and predictability",
      "State that is stored in local storage",
      "State that is only updated once",
    ],
    correctAnswer: "The practice of not directly modifying state objects or arrays, but instead creating new copies with the desired changes, which helps with performance optimization and predictability",
  },
  {
    id: 136,
    technology: "react",
    level: "Pro",
    question: "What are 'React DevTools' and how are they useful?",
    options: [
      "A tool for compiling React code",
      "Browser developer tools extensions that allow inspecting React component hierarchies, state, props, and performance, aiding in debugging and optimization",
      "A library for creating UI components",
      "A framework for testing React applications",
    ],
    correctAnswer: "Browser developer tools extensions that allow inspecting React component hierarchies, state, props, and performance, aiding in debugging and optimization",
  },
  {
    id: 137,
    technology: "react",
    level: "Pro",
    question: "Explain the purpose of 'memoization' with 'useCallback' and 'useMemo'.",
    options: [
      "To force components to re-render",
      "To optimize performance by caching expensive function definitions ('useCallback') or computed values ('useMemo') and only re-calculating them when their dependencies change",
      "To manage asynchronous operations",
      "To handle errors gracefully",
    ],
    correctAnswer: "To optimize performance by caching expensive function definitions ('useCallback') or computed values ('useMemo') and only re-calculating them when their dependencies change",
  },
  {
    id: 138,
    technology: "react",
    level: "Pro",
    question: "What is 'Concurrent Mode' in React and its goal?",
    options: [
      "A mode for running React applications synchronously",
      "A set of new features that allow React to work on multiple tasks at the same time, leading to more responsive user interfaces by making rendering interruptible",
      "A deprecated feature for backward compatibility",
      "A tool for server-side rendering only",
    ],
    correctAnswer: "A set of new features that allow React to work on multiple tasks at the same time, leading to more responsive user interfaces by making rendering interruptible",
  },

  // ================= Node.js =================
  {
    id: 13,
    technology: "node",
    level: "Beginner",
    question: "Node.js is built on which engine?",
    options: ["SpiderMonkey", "V8", "Chakra", "Rhino"],
    correctAnswer: "V8",
  },
  {
    id: 14,
    technology: "node",
    level: "Intermediate",
    question: "Which module is used for file handling?",
    options: ["fs", "path", "http", "os"],
    correctAnswer: "fs",
  },
  {
    id: 15,
    technology: "node",
    level: "Pro",
    question: "What is non-blocking I/O?",
    options: [
      "Stops execution",
      "Executes sequentially",
      "Allows parallel operations",
      "Blocks main thread",
    ],
    correctAnswer: "Allows parallel operations",
  },
  // Node.js - Beginner
  {
    id: 139,
    technology: "node",
    level: "Beginner",
    question: "What is Node.js primarily used for?",
    options: [
      "Frontend development",
      "Running JavaScript on the server-side",
      "Styling web pages",
      "Database management",
    ],
    correctAnswer: "Running JavaScript on the server-side",
  },
  {
    id: 140,
    technology: "node",
    level: "Beginner",
    question: "Which keyword is used to import modules in Node.js?",
    options: ["import", "include", "require", "attach"],
    correctAnswer: "require",
  },
  {
    id: 141,
    technology: "node",
    level: "Beginner",
    question: "What is npm?",
    options: [
      "Node Private Module",
      "Node Package Manager",
      "New Program Maker",
      "Network Protocol Module",
    ],
    correctAnswer: "Node Package Manager",
  },
  {
    id: 142,
    technology: "node",
    level: "Beginner",
    question: "How do you start a Node.js application from the command line?",
    options: ["run app.js", "node app.js", "start app.js", "execute app.js"],
    correctAnswer: "node app.js",
  },
  {
    id: 143,
    technology: "node",
    level: "Beginner",
    question: "Which module is used to create a basic web server in Node.js?",
    options: ["url", "path", "http", "fs"],
    correctAnswer: "http",
  },
  {
    id: 144,
    technology: "node",
    level: "Beginner",
    question: "What does the 'callback' function represent in Node.js asynchronous operations?",
    options: [
      "A function that returns a value immediately",
      "A function that is executed after a task completes",
      "A function that blocks the main thread",
      "A function that is called before an operation starts",
    ],
    correctAnswer: "A function that is executed after a task completes",
  },
  {
    id: 145,
    technology: "node",
    level: "Beginner",
    question: "Which global object provides information about the current Node.js process?",
    options: ["global", "console", "process", "os"],
    correctAnswer: "process",
  },
  {
    id: 146,
    technology: "node",
    level: "Beginner",
    question: "How do you define a constant variable in Node.js?",
    options: ["var", "let", "const", "def"],
    correctAnswer: "const",
  },
  {
    id: 147,
    technology: "node",
    level: "Beginner",
    question: "What is the purpose of 'package.json' file?",
    options: [
      "To store user data",
      "To define project metadata, scripts, and dependencies",
      "To store server configurations",
      "To cache static assets",
    ],
    correctAnswer: "To define project metadata, scripts, and dependencies",
  },
  {
    id: 148,
    technology: "node",
    level: "Beginner",
    question: "Which of the following is a core module in Node.js?",
    options: ["lodash", "express", "fs", "react"],
    correctAnswer: "fs",
  },
  // Node.js - Intermediate
  {
    id: 149,
    technology: "node",
    level: "Intermediate",
    question: "Explain the concept of the 'event-driven architecture' in Node.js.",
    options: [
      "Node.js executes code in a strict sequential order",
      "Node.js uses a single-threaded event loop to handle concurrent requests without blocking, reacting to events as they occur",
      "Node.js is primarily a multi-threaded application",
      "Node.js relies on client-side events only",
    ],
    correctAnswer: "Node.js uses a single-threaded event loop to handle concurrent requests without blocking, reacting to events as they occur",
  },
  {
    id: 150,
    technology: "node",
    level: "Intermediate",
    question: "What is 'middleware' in Express.js?",
    options: [
      "A type of database",
      "Functions that have access to the request object, the response object, and the next middleware function in the application's request-response cycle",
      "A client-side library",
      "A tool for creating APIs",
    ],
    correctAnswer: "Functions that have access to the request object, the response object, and the next middleware function in the application's request-response cycle",
  },
  {
    id: 151,
    technology: "node",
    level: "Intermediate",
    question: "How does Node.js handle concurrency with its single-threaded model?",
    options: [
      "By using multiple CPU cores directly",
      "By blocking operations until they complete",
      "Through its event loop, which processes asynchronous I/O operations without blocking the main thread",
      "By creating new threads for each request",
    ],
    correctAnswer: "Through its event loop, which processes asynchronous I/O operations without blocking the main thread",
  },
  {
    id: 152,
    technology: "node",
    level: "Intermediate",
    question: "What is 'Nodemon' and why is it useful?",
    options: [
      "A Node.js debugger",
      "A tool that automatically restarts the Node.js application when file changes are detected, saving manual restarts during development",
      "A Node.js package manager",
      "A tool for deploying Node.js applications",
    ],
    correctAnswer: "A tool that automatically restarts the Node.js application when file changes are detected, saving manual restarts during development",
  },
  {
    id: 153,
    technology: "node",
    level: "Intermediate",
    question: "What is a 'Stream' in Node.js?",
    options: [
      "A way to send data over a network",
      "An abstract interface for working with streaming data in Node.js, often used for efficient handling of large files or network data",
      "A type of database connection",
      "A real-time communication protocol",
    ],
    correctAnswer: "An abstract interface for working with streaming data in Node.js, often used for efficient handling of large files or network data",
  },
  {
    id: 154,
    technology: "node",
    level: "Intermediate",
    question: "Explain 'EventEmitter' in Node.js.",
    options: [
      "A way to handle HTTP requests",
      "A class that allows you to create and listen for custom events, forming the basis of Node.js's event-driven architecture",
      "A tool for managing asynchronous code",
      "A module for file I/O",
    ],
    correctAnswer: "A class that allows you to create and listen for custom events, forming the basis of Node.js's event-driven architecture",
  },
  {
    id: 155,
    technology: "node",
    level: "Intermediate",
    question: "What are environment variables in Node.js?",
    options: [
      "Variables defined within a JavaScript file",
      "Variables set outside the application's code, used to configure application behavior based on the environment (e.g., development, production)",
      "Variables specific to a function's scope",
      "Variables used for client-side configuration",
    ],
    correctAnswer: "Variables set outside the application's code, used to configure application behavior based on the environment (e.g., development, production)",
  },
  {
    id: 156,
    technology: "node",
    level: "Intermediate",
    question: "How do you handle errors in asynchronous Node.js code?",
    options: [
      "Using `try...catch` blocks for all async operations",
      "Through callback functions with an error-first argument, Promises with `.catch()`, or `async/await` with `try...catch`",
      "Node.js handles all errors automatically",
      "By ignoring errors for better performance",
    ],
    correctAnswer: "Through callback functions with an error-first argument, Promises with `.catch()`, or `async/await` with `try...catch`",
  },
  {
    id: 157,
    technology: "node",
    level: "Intermediate",
    question: "What is the purpose of 'path' module in Node.js?",
    options: [
      "To handle HTTP requests",
      "To interact with the file system",
      "To provide utilities for working with file and directory paths",
      "To manage process environment variables",
    ],
    correctAnswer: "To provide utilities for working with file and directory paths",
  },
  {
    id: 158,
    technology: "node",
    level: "Intermediate",
    question: "How do you expose a module's functionality in Node.js?",
    options: ["using `import` statement", "using `module.exports` or `exports`", "using `global` object", "using `public` keyword"],
    correctAnswer: "using `module.exports` or `exports`",
  },
  // Node.js - Pro
  {
    id: 159,
    technology: "node",
    level: "Pro",
    question: "Explain the 'Cluster' module in Node.js and its use case.",
    options: [
      "A module for creating distributed databases",
      "A module that allows you to create child processes that share server ports, enabling a single Node.js application to take advantage of multi-core systems (load balancing)",
      "A module for managing inter-process communication",
      "A tool for deploying Node.js applications to a cluster of servers",
    ],
    correctAnswer: "A module that allows you to create child processes that share server ports, enabling a single Node.js application to take advantage of multi-core systems (load balancing)",
  },
  {
    id: 160,
    technology: "node",
    level: "Pro",
    question: "What is 'Worker Threads' in Node.js and when would you use them?",
    options: [
      "A deprecated feature for multi-threading",
      "A module that allows offloading CPU-intensive JavaScript operations to separate threads, preventing the main event loop from being blocked",
      "A tool for creating background processes",
      "A method for managing asynchronous I/O",
    ],
    correctAnswer: "A module that allows offloading CPU-intensive JavaScript operations to separate threads, preventing the main event loop from being blocked",
  },
  {
    id: 161,
    technology: "node",
    level: "Pro",
    question: "Describe the 'libuv' library's role in Node.js.",
    options: [
      "It handles JavaScript parsing and execution",
      "It provides cross-platform asynchronous I/O, event loop, and thread pool functionalities that Node.js relies on for its non-blocking operations",
      "It is a database connector for Node.js",
      "It is a template engine for server-side rendering",
    ],
    correctAnswer: "It provides cross-platform asynchronous I/O, event loop, and thread pool functionalities that Node.js relies on for its non-blocking operations",
  },
  {
    id: 162,
    technology: "node",
    level: "Pro",
    question: "What is 'REPL' in Node.js?",
    options: [
      "A method for routing requests",
      "Read-Eval-Print Loop, an interactive shell environment for executing Node.js code line by line",
      "A tool for debugging Node.js applications",
      "A protocol for inter-process communication",
    ],
    correctAnswer: "Read-Eval-Print Loop, an interactive shell environment for executing Node.js code line by line",
  },
  {
    id: 163,
    technology: "node",
    level: "Pro",
    question: "Explain the concept of 'backpressure' in Node.js streams.",
    options: [
      "When a stream is too slow to process data",
      "A mechanism to handle the flow of data when a `Writable` stream cannot process data as fast as a `Readable` stream is producing it, preventing memory overload",
      "A type of error that occurs in streams",
      "A way to speed up stream processing",
    ],
    correctAnswer: "A mechanism to handle the flow of data when a `Writable` stream cannot process data as fast as a `Readable` stream is producing it, preventing memory overload",
  },
  {
    id: 164,
    technology: "node",
    level: "Pro",
    question: "How do you secure a Node.js API?",
    options: [
      "By only using HTTP",
      "Through practices like input validation, authentication (JWT, OAuth), authorization, HTTPS, rate limiting, and protecting against common vulnerabilities (XSS, CSRF)",
      "By hiding API endpoints",
      "By not exposing any data to the client",
    ],
    correctAnswer: "Through practices like input validation, authentication (JWT, OAuth), authorization, HTTPS, rate limiting, and protecting against common vulnerabilities (XSS, CSRF)",
  },
  {
    id: 165,
    technology: "node",
    level: "Pro",
    question: "What is 'PM2' and why is it used in Node.js production environments?",
    options: [
      "A Node.js testing framework",
      "A production process manager for Node.js applications that provides features like load balancing, automatic restarts, logging, and monitoring",
      "A database management tool",
      "A build tool for Node.js projects",
    ],
    correctAnswer: "A production process manager for Node.js applications that provides features like load balancing, automatic restarts, logging, and monitoring",
  },
  {
    id: 166,
    technology: "node",
    level: "Pro",
    question: "Explain the concept of 'buffers' in Node.js.",
    options: [
      "Temporary storage for JavaScript variables",
      "A temporary storage area for raw binary data, similar to an array of integers, used for operations with streams, file systems, and network protocols",
      "A type of cache for HTTP requests",
      "A mechanism for error handling",
    ],
    correctAnswer: "A temporary storage area for raw binary data, similar to an array of integers, used for operations with streams, file systems, and network protocols",
  },
  {
    id: 167,
    technology: "node",
    level: "Pro",
    question: "What is 'DNS prefetching' and how can it be implemented in Node.js?",
    options: [
      "A method for speeding up database queries",
      "Resolving domain names in advance to reduce latency for future requests; in Node.js, you'd typically handle this on the client-side or through HTTP headers, not directly in Node.js core logic",
      "A way to cache DNS records",
      "A network security measure",
    ],
    correctAnswer: "Resolving domain names in advance to reduce latency for future requests; in Node.js, you'd typically handle this on the client-side or through HTTP headers, not directly in Node.js core logic",
  },
  {
    id: 168,
    technology: "node",
    level: "Pro",
    question: "How do you implement WebSockets in Node.js?",
    options: [
      "By using the `http` module only",
      "By using libraries like `ws` or `Socket.IO` to enable real-time, bidirectional communication between the client and server over a single, long-lived TCP connection",
      "WebSockets are not supported in Node.js",
      "By continuously polling the server with HTTP requests",
    ],
    correctAnswer: "By using libraries like `ws` or `Socket.IO` to enable real-time, bidirectional communication between the client and server over a single, long-lived TCP connection",
  },

  // ================= MongoDB =================
  {
    id: 16,
    technology: "mongodb",
    level: "Beginner",
    question: "MongoDB stores data as?",
    options: ["Tables", "Rows", "Documents", "Columns"],
    correctAnswer: "Documents",
  },
  {
    id: 17,
    technology: "mongodb",
    level: "Intermediate",
    question: "Which method retrieves multiple documents?",
    options: ["findOne()", "find()", "get()", "search()"],
    correctAnswer: "find()",
  },
  {
    id: 18,
    technology: "mongodb",
    level: "Pro",
    question: "Why are indexes used in MongoDB?",
    options: [
      "Reduce storage",
      "Improve query performance",
      "Encrypt data",
      "Validate schema",
    ],
    correctAnswer: "Improve query performance",
  },
  // MongoDB - Beginner
  {
    id: 169,
    technology: "mongodb",
    level: "Beginner",
    question: "What type of database is MongoDB?",
    options: ["Relational", "SQL", "NoSQL", "Graph"],
    correctAnswer: "NoSQL",
  },
  {
    id: 170,
    technology: "mongodb",
    level: "Beginner",
    question: "What is a 'collection' in MongoDB?",
    options: [
      "A table in a relational database",
      "A group of SQL queries",
      "A group of documents, equivalent to a table in relational databases",
      "A single record in the database",
    ],
    correctAnswer: "A group of documents, equivalent to a table in relational databases",
  },
  {
    id: 171,
    technology: "mongodb",
    level: "Beginner",
    question: "Which command is used to connect to a MongoDB database?",
    options: ["connect()", "use databaseName", "db.connect()", "mongoConnect()"],
    correctAnswer: "use databaseName",
  },
  {
    id: 172,
    technology: "mongodb",
    level: "Beginner",
    question: "What is a 'document' in MongoDB?",
    options: [
      "A text file",
      "A set of key-value pairs, similar to JSON objects, which are the basic unit of data in MongoDB",
      "A row in a relational database",
      "A schema definition",
    ],
    correctAnswer: "A set of key-value pairs, similar to JSON objects, which are the basic unit of data in MongoDB",
  },
  {
    id: 173,
    technology: "mongodb",
    level: "Beginner",
    question: "Which operation is used to insert a single document into a collection?",
    options: ["insert()", "add()", "create()", "insertOne()"],
    correctAnswer: "insertOne()",
  },
  {
    id: 174,
    technology: "mongodb",
    level: "Beginner",
    question: "How do you select all documents from a collection named 'users'?",
    options: ["db.users.select()", "db.users.get()", "db.users.find({})", "db.users.searchAll()"],
    correctAnswer: "db.users.find({})",
  },
  {
    id: 175,
    technology: "mongodb",
    level: "Beginner",
    question: "Which method is used to update an existing document?",
    options: ["update()", "modify()", "edit()", "updateOne()"],
    correctAnswer: "updateOne()",
  },
  {
    id: 176,
    technology: "mongodb",
    level: "Beginner",
    question: "What is the primary key in MongoDB called by default?",
    options: ["id", "primaryId", "_id", "docId"],
    correctAnswer: "_id",
  },
  {
    id: 177,
    technology: "mongodb",
    level: "Beginner",
    question: "Which command removes documents from a collection?",
    options: ["delete()", "remove()", "clear()", "deleteOne()"],
    correctAnswer: "deleteOne()",
  },
  {
    id: 178,
    technology: "mongodb",
    level: "Beginner",
    question: "What does 'mongod' refer to?",
    options: [
      "The MongoDB client",
      "The MongoDB database daemon/server process",
      "A MongoDB query language",
      "A MongoDB utility for backup",
    ],
    correctAnswer: "The MongoDB database daemon/server process",
  }
,// Beginner Level Questions (10 questions)
{
  id: 179,
  technology: "mongodb",
  level: "Beginner",
  question: "Which format does MongoDB use to store documents?",
  options: ["XML", "CSV", "BSON (Binary JSON)", "Plain text"],
  correctAnswer: "BSON (Binary JSON)",
},
{
  id: 180,
  technology: "mongodb",
  level: "Beginner",
  question: "How do you insert multiple documents at once in MongoDB?",
  options: ["insertAll()", "insertMany()", "bulkInsert()", "addMultiple()"],
  correctAnswer: "insertMany()",
},
{
  id: 181,
  technology: "mongodb",
  level: "Beginner",
  question: "Which method is used to find a single document in a collection?",
  options: ["findFirst()", "findOne()", "getOne()", "selectOne()"],
  correctAnswer: "findOne()",
},
{
  id: 182,
  technology: "mongodb",
  level: "Beginner",
  question: "What command lists all databases in MongoDB?",
  options: ["list databases", "show databases", "show dbs", "get databases"],
  correctAnswer: "show dbs",
},
{
  id: 183,
  technology: "mongodb",
  level: "Beginner",
  question: "Which operator is used to update specific fields in a document?",
  options: ["$modify", "$set", "$update", "$change"],
  correctAnswer: "$set",
},
{
  id: 184,
  technology: "mongodb",
  level: "Beginner",
  question: "How do you count the number of documents in a collection?",
  options: ["db.collection.count()", "db.collection.countDocuments()", "db.collection.size()", "db.collection.length()"],
  correctAnswer: "db.collection.countDocuments()",
},
{
  id: 185,
  technology: "mongodb",
  level: "Beginner",
  question: "What does the 'mongo' or 'mongosh' command do?",
  options: [
    "Starts the MongoDB server",
    "Opens the MongoDB shell client to interact with databases",
    "Creates a new database",
    "Backs up MongoDB data",
  ],
  correctAnswer: "Opens the MongoDB shell client to interact with databases",
},
{
  id: 186,
  technology: "mongodb",
  level: "Beginner",
  question: "Which method removes all documents from a collection?",
  options: ["db.collection.removeAll()", "db.collection.deleteMany({})", "db.collection.clear()", "db.collection.truncate()"],
  correctAnswer: "db.collection.deleteMany({})",
},
{
  id: 187,
  technology: "mongodb",
  level: "Beginner",
  question: "How do you display all collections in the current database?",
  options: ["list collections", "show collections", "get collections", "display collections"],
  correctAnswer: "show collections",
},
{
  id: 188,
  technology: "mongodb",
  level: "Beginner",
  question: "What is the default port number for MongoDB?",
  options: ["3306", "5432", "27017", "8080"],
  correctAnswer: "27017",
},

// Intermediate Level Questions (5 questions)
{
  id: 189,
  technology: "mongodb",
  level: "Intermediate",
  question: "Which operator is used to match documents where a field contains any value from a specified array?",
  options: ["$in", "$contains", "$match", "$any"],
  correctAnswer: "$in",
},
{
  id: 190,
  technology: "mongodb",
  level: "Intermediate",
  question: "What is the purpose of an index in MongoDB?",
  options: [
    "To store backups of data",
    "To improve query performance by allowing faster data retrieval",
    "To encrypt documents",
    "To create relationships between collections",
  ],
  correctAnswer: "To improve query performance by allowing faster data retrieval",
},
{
  id: 191,
  technology: "mongodb",
  level: "Intermediate",
  question: "Which aggregation stage is used to filter documents?",
  options: ["$filter", "$match", "$where", "$select"],
  correctAnswer: "$match",
},
{
  id: 192,
  technology: "mongodb",
  level: "Intermediate",
  question: "What does the $group stage do in an aggregation pipeline?",
  options: [
    "Filters documents based on criteria",
    "Groups documents by a specified field and performs accumulator operations",
    "Sorts documents",
    "Joins collections together",
  ],
  correctAnswer: "Groups documents by a specified field and performs accumulator operations",
},
{
  id: 193,
  technology: "mongodb",
  level: "Intermediate",
  question: "Which method creates an index on a field in MongoDB?",
  options: ["db.collection.addIndex()", "db.collection.createIndex()", "db.collection.index()", "db.collection.newIndex()"],
  correctAnswer: "db.collection.createIndex()",
}]